<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<OutputPath>..\..\Build</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <Target Name="EncryptAssemblies" AfterTargets="Publish">
    <ItemGroup>
	  <PublishDir Include="$(PublishDir)" />
      <PdbFiles Include="$(PublishDir)*.pdb" />
	</ItemGroup>

	<Delete Files="@(PdbFiles)" />
  </Target>
</Project>
